
INSERT INTO USER (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, ENABLED, LASTPASSWORDRESETDATE) VALUES (1, 'admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin', 'admin', 'admin@admin.com', 1, PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));
INSERT INTO USER (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, ENABLED, LASTPASSWORDRESETDATE) VALUES (2, 'user', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user', 'user', 'enabled@user.com', 1, PARSEDATETIME('01-01-2016','dd-MM-yyyy'));
INSERT INTO USER (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, ENABLED, LASTPASSWORDRESETDATE) VALUES (3, 'disabled', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user', 'user', 'disabled@user.com', 0, PARSEDATETIME('01-01-2016','dd-MM-yyyy'));

INSERT INTO AUTHORITY (ID, NAME) VALUES (1, 'ROLE_USER');
INSERT INTO AUTHORITY (ID, NAME) VALUES (2, 'ROLE_ADMIN');


INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (1, 2);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (2, 1);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (3, 1);



INSERT INTO CAR (CAR_NAME,CARBURANT,NB_PORTES,NB_PLACES_ASSIS,TYPE_BOITE,RELEASE_YEAR,PRICE,AVAILABLE,IMG_URL) VALUES ('merco','Essence',5,5,'Manuelle',2018,50,'Dispo'
,null
);

INSERT INTO CAR (CAR_NAME,CARBURANT,NB_PORTES,NB_PLACES_ASSIS,TYPE_BOITE,RELEASE_YEAR,PRICE,AVAILABLE,IMG_URL) VALUES ('Opel','Essence',5,5,'Manuelle',2018,50,'Dispo'
,'https://photos.tf1.fr/940/531/opel-astra-2015-1-0c6054-0@1x.jpg'
);


INSERT INTO CLIENT (USERNAME, PASSWORD, LAST_NAME, FIRST_NAME, GENDER, EMAIL) VALUES ('Xander','***','cage','christ','M','xander@hotmail.com');

INSERT INTO CLIENT (USERNAME, PASSWORD, LAST_NAME, FIRST_NAME, GENDER, EMAIL) VALUES ('Deoking','***','julien','dunia','M','deoking@hotmail.com');

INSERT INTO CLIENT (USERNAME, PASSWORD, LAST_NAME, FIRST_NAME, GENDER, EMAIL) VALUES ('Mikasa','***','ackerman','mikasa','F','mikasa@hotmail.com');
